services:
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  arangodb:
    image: arangodb:latest
    environment:
      ARANGO_NO_AUTH: 1
    ports:
      - "8529:8529"
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps

  notifications_app:
    build:
      context: "../../"
      dockerfile: "apps/notificationsApp/Dockerfile"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    command: --spring.profiles.active=docker
    #    restart: on-failure
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
      - arangodb

volumes:
  arangodb_data_container:
  arangodb_apps_data_container:
