services:
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  chat_app:
    build:
      context: "../../"
      dockerfile: "apps/chatApp/Dockerfile"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    #    restart: on-failure
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
